name: Demo update
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  updateBranch:
    name: Update demo branch
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'canonical' }}
    steps:
    - uses: actions/checkout@v6
    - name: Fetch rebase and push
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.email "github-action@example.com"
        git config --global user.name "GitHub Action"
        git branch demo
        git checkout demo
        touch wip-file
        git add wip-file
        git commit -am "wip"
        git push origin demo --force
